language: c++
compiler: g++
sudo: required
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq g++-5 gtest
    - (cd /usr/src/gtest; sudo cmake . && sudo make && sudo cp libgtest.a /usr/lib/ && sudo cp -R include/gtest/ /usr/include/)
    - export CXX_OVERRIDE="g++-5"
script: make build && (cd test/; make all && ./unittest)
notifications:
email:
    - wr0112358@gmail.com
